### ISSUE TITLE
I want to learn more about this project，Please provide me a url

### ISSUE THREAD

**Issue by yangnan456** [TrevorBurgoyne/GPS-Denied-Nav#2]
![image](https://github.com/TrevorBurgoyne/GPS-Denied-Nav/assets/99865141/dde5353c-7bce-4bab-b47d-e03eb5e37d92)

I noticed that the PDF in your project mentions the URL of a book, but there is no link attached. Could you please advise on how to obtain the link to the book that this project depends on

**Comment by TrevorBurgoyne** [comment]
The book referenced in `GNSS INS Filters/` is [GNSS Applications and Methods](https://us.artechhouse.com/GNSS-Applications-and-Methods-P1297.aspx) by Demoz Gebre-Egziabher & Scott Gleason. I will update the readme to include this.
